### ISSUE TITLE
Bug: in landscape no show ...

### ISSUE THREAD

**Issue by webserveis** [Blogcat/Android-ExpandableTextView#1]
If you change the landscape orientation does not appear ellipsis end (...)

**Comment by Cliffus** [comment]
Hi

thanks for reporting this issue!
can you provide me the exact stept to reproduce?

**Comment by webserveis** [comment]
If when the activity is displayed , it looks good, with ellipsis end
When rotate device, the ellipsis not appear.

Of the three devices I frame
I only occurs with  MotoG version 5.1 Lollipop the others are perfectly displayed.

In the future it will be possible to support api 15 ?
and change animation with https://github.com/MasayukiSuda/EasingInterpolator

**Comment by Cliffus** [comment]
thanks for the information! 
I'll try to fix this issue in the upcoming days / week and let you know when I'm ready.

Concerning your other questions: I'm happy with these feature requests, kan you make separate tickets for them? This way, you (and others) can follow up the status.

Thanks again,
Cliff

**Comment by Cliffus** [comment]
are you using android:configChanges="" for your Activities in your Android manifest? I'm only able to reproduce the issue with android:configChanges="" defined.

I'll let you know when the issue is fixed

**Comment by webserveis** [comment]
Not apply configchange , maybe the problem is in the message body , spaces., semicolons and breakpoints. Because sometimes well located ellipses and other bad , that only landscape

**Comment by Cliffus** [comment]
thanks for the screenshots, they are very helpful!

ExpandableTextView extends from TextView, so it depends on the native TextView class for showing the ellipsis. Can you check if the issue also occurs when changing the ExpandableTextView to a regular TextView (with the exact same layout attributes)?

In the the meantime, I'm already fixing some issues concerning orientation changes when using android:configChanges="" in your Android Manifest.

**Comment by webserveis** [comment]
In my test , it works perfectly with the capture text must be some Json the TextView there are characters that do not like in my App.
You can close the bug

**Comment by Cliffus** [comment]
ok, thank you for verifying!
