### ISSUE TITLE
Doesn't scroll to button on collapse in long texts

### ISSUE THREAD

**Issue by zakusha** [Blogcat/Android-ExpandableTextView#10]
https://www.dropbox.com/s/95pic2wumblc38n/device-2016-11-01-161547.mp4?dl=0
see the screen record example

**Comment by Cliffus** [comment]
Hi

ExpandableTextview is only responsible for expanding and collapsing its inner text. It doesn't know if it's contained in a scroll view, so you will have to implement this scrolling behaviour.

Good luck!
Cliff
