### ISSUE TITLE
delay while collapsing the text

### ISSUE THREAD

**Issue by KadamMangesh** [Blogcat/Android-ExpandableTextView#11]
I am using down arrow and up arrow for collapse and expand. Expanding text works in sync with down arrow as this arrow is statically defined in layout file. I am facing problem while collapsing. I am using below code to change the image icon

`  mExpandableTextView.setOnExpandListener(new ExpandableTextView.OnExpandListener() {
            @Override
            public void onExpand(ExpandableTextView view) {
                mImageView.setImageResource(R.drawable.up_arrow);
            }

            @Override
            public void onCollapse(ExpandableTextView view) {

                mImageView.setImageResource(R.drawable.down_arrow);
               
            }
        });`

but it seems drawable is updated immediately but Textview takes a time to collapse. Can you please help me on this?

**Comment by Cliffus** [comment]
Hi

thanks for reporting this issue. It's correct that the onCollapse() method is called immediately, and doesn't wait for the animation to finish. What you could do is use a Handler and post a delayed runnable when onCollapse() is being called, using the same amount of milliseconds the animation takes to finish.

Good luck!
Cliff
