### ISSUE TITLE
Programmatically create ExpandableTextView  with Maxline ?

### ISSUE THREAD

**Issue by chihung93** [Blogcat/Android-ExpandableTextView#13]
Hello ,
I wanna set up maxLine with code.
I tried to set maxLines in your code, but it does not work.
Tks.

**Comment by Cliffus** [comment]
Hi

first of all sorry for the late response to your question. Currently this is not possible with this library, and it's a bit on hold for now. Feel free to fork this repository and implement it yourself. When finished, I'll gladly review your pull request and merge it into the master branch.

If you're not able to do this, please let me know, I'll see what I can do to help you.

Kind regards
Cliff

**Comment by chihung93** [comment]
Hello @Cliffus 
Now that I've created a library for myself, I'm happy to share this with you.
Have a nice day.

https://github.com/chihung93/ExpandableTextView

**Comment by Cliffus** [comment]
Hi

thanks for sharing your solution with me.

I see that you borrowed some code snippets from this library. I've put a lot of time in finding this solution, would you mind referring to this Github page? I'll do the same for you if I borrow some ideas from yours.

Thanks a lot!
