### ISSUE TITLE
Android 8 issue

### ISSUE THREAD

**Issue by sinandizdarevic** [Blogcat/Android-ExpandableTextView#17]
It doesn't work anymore on Android 8 (Oreo). TextView is auto expanded and it's not possible to collapse it. Tested on Nexus 6P device.

**Comment by Cliffus** [comment]
Hi

thanks for reporting this issue. I'll try to fix this issue asap, because I also need this fix for my own applications ;-)

Best regards
Cliff

**Comment by sinandizdarevic** [comment]
Thanks Cliff. :)

**Comment by giffell** [comment]
Thanks you for the library) I hope it will be fixed very soon =)

**Comment by Cliffus** [comment]
This issue will be fixed in one of the next 2 weeks, I'll keep you posted!

**Comment by Cliffus** [comment]
Just letting you know I've started fixing the issue today

**Comment by Cliffus** [comment]
This issue seems to only occur when maxLines = 0, can you guys confirm this?

**Comment by giffell** [comment]
@Cliffus I used maxLines = 0

**Comment by sinandizdarevic** [comment]
Yes. it's issue only when maxLines = 0. But I need to have it on 0. If it's not doable I will try some workaround to fix it. 

Anyway. Thanks!

**Comment by Cliffus** [comment]
@sinandizdarevic thanks for your feedback. I'm fixing the issue as we speak, but I didn't find a solution yet. I'll keep you guys posted!

**Comment by Cliffus** [comment]
Hi all

this issue has been resolved in version 1.0.5

Regards!
Cliff

**Comment by sinandizdarevic** [comment]
Everything works fine with maxLines = 0. 

Thanks!
