### ISSUE TITLE
Extras \n\n on expand

### ISSUE THREAD

**Issue by Johnsonmaung** [Blogcat/Android-ExpandableTextView#20]
Normal State:
Nulla malesuada urna et bibendum imperdiet.

Expand State:
Nulla malesuada urna et bibendum imperdiet.\n\n

**Comment by Cliffus** [comment]
Hi Johnsonmaung

can you please describe your issue a bit more in detail? How can I reproduce this issue?

Thanks!
Cliff

**Comment by Johnsonmaung** [comment]
@Cliffus Thanks for your reply. Actually it's android Html.fromHtml() bug on rendering `<p></p>` tag. Found solution by trim(). Thanks.

**Comment by Cliffus** [comment]
great, thanks for year feedback!
