### ISSUE TITLE
Api Support >15

### ISSUE THREAD

**Issue by webserveis** [Blogcat/Android-ExpandableTextView#3]
It is possible in the future that can withstand minimal version of the api 15?

**Comment by Cliffus** [comment]
according to the build.gradle file in the library module of this project, minSdkVersion is set to 14:

https://github.com/Blogcat/Android-ExpandableTextView/blob/release/1.0.1/expandabletextview/build.gradle

do you have issues using the ExpandableTextView class on AP leven 14 and 15?

**Comment by Cliffus** [comment]
did you already find some time to validate above information? thanks!

**Comment by Cliffus** [comment]
Closing this issue for now, but definitely let me know if you experience any issues related to minSdkVersion
