### ISSUE TITLE
Feature custom Animation expand/collapse

### ISSUE THREAD

**Issue by webserveis** [Blogcat/Android-ExpandableTextView#4]
.setInterpolator()

Add custom interpolator for animation collapse and expand, usage with [EasingInterpolator](https://github.com/MasayukiSuda/EasingInterpolator)

**Comment by Cliffus** [comment]
I checked out the source code of the EasingInterpolator library, and it seems that this interpolator implements the [TimeInterpolator interface](https://developer.android.com/reference/android/animation/TimeInterpolator.html) from the Android framework.

```
public class EasingInterpolator implements TimeInterpolator {

    private final Ease ease;

    public EasingInterpolator(@NonNull Ease ease) {
        this.ease = ease;
    }

    @Override
    public float getInterpolation(float input) {
        return EasingProvider.get(this.ease, input);
    }

    public Ease getEase() {
        return ease;
    }
}
```

https://github.com/MasayukiSuda/EasingInterpolator/blob/master/ei/src/main/java/com/daasuu/ei/EasingInterpolator.java

Version 1.0.1 of ExpandableTextView added support for TimeInterpolators:

```
   /**
     * Sets a {@link TimeInterpolator} for expanding and collapsing.
     * @param interpolator the interpolator
     */
    public void setInterpolator(final TimeInterpolator interpolator)
    {
        this.expandInterpolator = interpolator;
        this.collapseInterpolator = interpolator;
    }

    /**
     * Sets a {@link TimeInterpolator} for expanding.
     * @param expandInterpolator the interpolator
     */
    public void setExpandInterpolator(final TimeInterpolator expandInterpolator)
    {
        this.expandInterpolator = expandInterpolator;
    }

    /**
     * Sets a {@link TimeInterpolator} for collpasing.
     * @param collapseInterpolator the interpolator
     */
    public void setCollapseInterpolator(final TimeInterpolator collapseInterpolator)
    {
        this.collapseInterpolator = collapseInterpolator;
    }
```

So the only thing you have to do is add ExpandableTextView (1.0.1) and EasingInterpolator as a dependency to your project and set EasingInterpolator as interpolator for ExpandableTextView.

Can you confirm this works for you?

**Comment by webserveis** [comment]
It works well with EasingInterpolator library.
