### ISSUE TITLE
TextView not expanding or collapsing when using ExpandableTextView

### ISSUE THREAD

**Issue by tudorific** [Blogcat/Android-ExpandableTextView#7]
Hi,

Thanks for creating this ExpandableTextView, it is exactly what I am looking to do, however, I'm not sure what I am missing because the textview is not expanding or collapsing for me.

I have the following ExpandableTextView in my layout:

```
<at.blogc.android.views.ExpandableTextView
                android:id="@+id/tv_JobDesc"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:textSize="14sp"
                android:textColor="@color/laborswipe_darkgray"
                android:text="aasdf
                 a
                 a
                 a
                 a
                 "
                android:maxLines="5"
                android:ellipsize="end"
                android:background="@color/white"/>
```

I am trying to expand the ExpandableTextView in my adapter class like this:

```
public class JobAdapter extends ArrayAdapter<Job> {
    private final Context context;
    private final ArrayList<Job> jobs;
    private final int layoutResourceId;
    private ExpandableTextView desc = null;
    private Button expand = null;
    private boolean isExpanded = false;

    public JobAdapter(Context context, int layoutResourceId, ArrayList<Job> jobs) {
        super(context, layoutResourceId, jobs);
        this.context = context;
        this.jobs = jobs;
        this.layoutResourceId = layoutResourceId;
    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        View view = convertView;
        ViewHolder holder = null;

        LayoutInflater inflater = (LayoutInflater) context.getSystemService((Activity.LAYOUT_INFLATER_SERVICE));

        if (view == null) {
            view = inflater.inflate(layoutResourceId, parent, false);

            holder = new ViewHolder();
            holder.title = (TextView)view.findViewById(R.id.tv_jobTitle);
            //holder.description = (ExpandableTextView)view.findViewById(R.id.tv_JobDesc);
            desc = (ExpandableTextView)view.findViewById(R.id.tv_JobDesc);
            //holder.expand = (Button) view.findViewById(R.id.btn_descExpand);
            expand = (Button) view.findViewById(R.id.btn_descExpand);

            view.setTag(holder);
        } else {
            holder = (ViewHolder)view.getTag();
        }

        Job j = jobs.get(position);

        holder.title.setText(j.getJobTitle());
        //holder.description.setText(j.getDescription());
        desc.setText(j.getDescription());
        // set animation duration via code, but preferable in your layout files by using the animation_duration attribute
        desc.setAnimationDuration(1000L);

        // set interpolators for both expanding and collapsing animations
        desc.setInterpolator(new OvershootInterpolator());

        // or set them separately
        desc.setExpandInterpolator(new OvershootInterpolator());
        desc.setCollapseInterpolator(new OvershootInterpolator());

        //when user clicks the expand/collapse button, expand or collapse the description field
        holder.expand.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                System.out.println("Expanding Button Clicked!");
                desc.toggle();
                expand.setText(desc.isExpanded() ? "Collapse" : "Expand");
            }
        });

        // listen for expand / collapse events
        desc.setOnExpandListener(new ExpandableTextView.OnExpandListener() {
            @Override
            public void onExpand(final ExpandableTextView view) {
                Log.d("TextView", "ExpandableTextView expanded");
            }

            @Override
            public void onCollapse(final ExpandableTextView view) {
                Log.d("TextView", "ExpandableTextView collapsed");
            }
        });

        return view;
    }

    static class ViewHolder
    {
        TextView title;
        ExpandableTextView description;
        Button expand;
    }
}

```

I'm not sure what I am missing, am I not able to use the ExpandableTextView in a custom adapter?

Thanks for the help!

**Comment by Cliffus** [comment]
Hi!

thanks for using ExpandabletextView and reporting this issue. I'll try to reproduce this issue and provide a solution / fix for your problem. In the meantime, can you double check that the length of the job descriptions exceeds the max length of the TextView? 

How urgent do you need a solution for this issue?

Thanks again!

**Comment by tudorific** [comment]
Thanks @Cliffus , its not super urgent, just using this ExpandableTextView on a project I am working on. I'm pretty sure it has to do with m layout as it is a bit complex. I've attached my jobcard layout file to this comment, as well the main layout that my activity uses. This activity combines the jobcard layout used by the custom adapter and the main layout. Please let me know if there is more I can provide to help you help me :) 
[activity_main.txt](https://github.com/Blogcat/Android-ExpandableTextView/files/382821/activity_main.txt)
[jobcard.txt](https://github.com/Blogcat/Android-ExpandableTextView/files/382822/jobcard.txt)

**Comment by Cliffus** [comment]
Thanks for providing your layout files, this will help me a lot! 

I'll keep you posted.

**Comment by Cliffus** [comment]
I used the job card layout as the layout for my Main activity, and it works like a charm. I noticed you use the SwipeCard library (https://github.com/Diolor/Swipecards) in your application. It is possible that it contains some kind of layouting / measuring issue, causing ExpandableTextview not to work properly.

One other thing you can try is to remove the interpolator stuff (setExpandInterpolator() and setCollapseInterpolator()). Another user reported to me that she had issues when using the OvershootInterpolator, but I doubt this will fix your issue.

**Comment by tudorific** [comment]
Nope, removing the interpolator lines did not fix it for me. When you used the job card layout, did you use it with the` <merge>` similar to my activity_main.xml? Do you think that has something to do with it possibly?

**Comment by Cliffus** [comment]
I'm also using the <merge> tags, but it is still working over here. There are some things you can try to do:

- try to remove the fixed heights on your viewgroups / layouts, and replace them with wrap_content. It's possible that because of the fixed heights, the TextView doesn't expand properly
- simplify your layout file, maybe you can achieve the same layout by only using 1 RelativeLayout containing all the child views
- wrap the ExpandableTextView with a FrameLayout, but I don't think this will help for you

**Comment by tudorific** [comment]
@Cliffus thanks for the help! I tried changing my layout to this:

```
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <at.blogc.android.views.ExpandableTextView
        android:id="@+id/tv_JobDesc"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="asdfaa
        \n aaaaaaaaa
        \n aaaaaaa
        \n aaaaaaa
        \n aaaaaaaaaaa
        \n aaaaaaaaa
        \n aaaaaaaaaa
        \n aaaaaaaaa
        \n aaaaaaaa"
        android:maxLines="2"
        android:ellipsize="end"
        app:animation_duration="1000"/>

    <!-- Optional parameter animation_duration: sets the duration of the expand animation -->

    <Button
        android:id="@+id/btn_descExpand"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="expand"/>

</LinearLayout>
```

The field still does not expand, do you think this has to do with using a custom adapter? I figured using a simple layout would work, but still no expanding textview so it must be my the Swipecards or the custom adapter I am using...

**Comment by Cliffus** [comment]
it seems to me that this could be an issue in the SwipeCards library because ExpandableTextView doesn't override any setText() methods, it only alters layout params while animating.

maybe you can report the issue over there, and replace the ExpandableTextView with a default TextView? (because the setText() method also doesn't work for you)

**Comment by tudorific** [comment]
Thanks for all the help @Cliffus! I have reported this issue on the SwipeCards library, hopefully someone responds so I can get this resolved :). I will close this issue now.

**Comment by Cliffus** [comment]
you're welcome!
if you need help with any other issues, let me know!
